version: "3.8"

services:
  games-browser-frontend:
    image: node:22-alpine
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"                     # Vite default dev server port
    environment:
      - NODE_ENV=develop
    working_dir: /app
    command: ["sh", "-c", "npm install --legacy-peer-deps && npm run build &&  npm run preview -- --host 0.0.0.0"]
    depends_on:
      - games-browser-backend

  games-browser-backend:
    image: node:22-alpine
    volumes:
      - ./backend:/app
      - ${GAMES_PATH}:/games:ro
    ports:
      - "3001:3001"                     # backend API
    environment:
      - NODE_ENV=development
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
    working_dir: /app
    command: ["sh", "-c", "npm install && npm run build && npm run start"]
